### ISSUE TITLE
<15.1.0> Correct way to decipher urls (Client: TV) ?

### ISSUE THREAD

**Issue by theone2277** [LuanRT/YouTube.js#1031]
### Question

I have encountered a bug.

Here is the code:
```ts
import { Innertube, UniversalCache } from 'youtubei.js';
import { join } from 'node:path';

const SEARCH_QUERY = 'Hey Jude';
const TARGET_ITAG = 18;
const COOKIE_FILE_PATH = 'cookies.txt';

async function getCookieFileContent(cookieFilePath: string): Promise<string> {
    const cookieFile = Bun.file(cookieFilePath);
    if (!(await cookieFile.exists())) {
      console.warn(
        `🔴 WARNING: Cookie file not found at '${cookieFilePath}'. The application will run in unauthenticated mode.`
      );
      return '';
    }
    try {
      const cookieFileContent = await cookieFile.text();
      console.log(`✅ Cookies loaded successfully from ${cookieFilePath}.`);
      return cookieFileContent;
    } catch (error) {
      console.error('CRITICAL: Error reading cookie file:', error);
      return '';
    }
}

async function main() {
    let videoId: string | undefined;

    try {
        console.log("Initializing YouTube client...");
        const cookie = await getCookieFileContent(COOKIE_FILE_PATH);
        const yt = await Innertube.create({ cookie, cache: new UniversalCache(false) });

        console.log(`Searching YouTube Music for "${SEARCH_QUERY}"...`);
        const search = await yt.music.search(SEARCH_QUERY, { type: 'song' });

        if (!search.songs?.contents.length) {
            throw new Error(`Could not find any song results for "${SEARCH_QUERY}".`);
        }

        const songToDownload = search.songs.contents[0];
        videoId = songToDownload.id;
        const songTitle = songToDownload.title || 'Untitled Song';

        if (!videoId) {
            throw new Error('Could not extract video ID from search results.');
        }

        console.log(`\nFound: "${songTitle}" (ID: ${videoId}). Fetching info...`);
        const info = await yt.getInfo(videoId, { client: 'TV' });

        const infoJsonPath = join(process.cwd(), `zzz.json`);
        await Bun.write(infoJsonPath, JSON.stringify(info, null, 2));
        console.log(`✅ Full getInfo response saved to: ${infoJsonPath}`);

        console.log('Useing Manual Decipher from `getInfo`');
        try {
            const format = info.streaming_data?.formats.find(f => f.itag === TARGET_ITAG);
            if (!format) {
                throw new Error(`Could not find format with itag ${TARGET_ITAG}.`);
            }
            if (!format.signature_cipher && !format.cipher) {
                throw new Error(`Found itag ${TARGET_ITAG}, but it does not contain a cipher.`);
            }

            console.log(`Found itag ${TARGET_ITAG} with a cipher. Attempting to decipher...`);
            const decipheredUrl = format.decipher();
            
            if (!decipheredUrl) {
                throw new Error('The .decipher() method was unsuccessful and returned an empty string.');
            }
            
            console.log('\n✅ SUCCESS: Manually deciphered URL:');
            console.log(decipheredUrl);
            return;

        } catch (error) {
            console.error('\n❌ FAILED: An error occurred during manual deciphering.');
            console.error(`❌ Exact Error: ${error instanceof Error ? error.message : String(error)}`);
        }
    } catch (error) {
        console.error('Error:', error);
        process.exit(1);
    }
}

main();
```

I am receiving:
```tex
Initializing YouTube client...
✅ Cookies loaded successfully from cookies1.txt.
Searching YouTube Music for "Hey Jude"...

Found: "Hey Jude" (ID: mQER0A0ej0M). Fetching info...
✅ Full getInfo response saved to: /home/admin/zzz.json

Using Manual Decipher from `getInfo`
Found itag 18 with a cipher. Attempting to decipher...

❌ FAILED: An error occurred during manual deciphering.
❌ Exact Error: The .decipher() method was unsuccessful and returned an empty string.
```

How do I decipher urls correctly?

### Checklist

- [x] I am running the latest version.
- [x] I checked the documentation and found no answer.
- [x] I have searched the existing issues and made sure this is not a duplicate.
- [x] I have provided sufficient information.

**Comment by Nansess** [comment]
> ### Question
> 
> I have encountered a bug.
> 
> Here is the code:
> ```ts
> import { Innertube, UniversalCache } from 'youtubei.js';
> import { join } from 'node:path';
> 
> const SEARCH_QUERY = 'Hey Jude';
> const TARGET_ITAG = 18;
> const COOKIE_FILE_PATH = 'cookies.txt';
> 
> async function getCookieFileContent(cookieFilePath: string): Promise<string> {
>     const cookieFile = Bun.file(cookieFilePath);
>     if (!(await cookieFile.exists())) {
>       console.warn(
>         `🔴 WARNING: Cookie file not found at '${cookieFilePath}'. The application will run in unauthenticated mode.`
>       );
>       return '';
>     }
>     try {
>       const cookieFileContent = await cookieFile.text();
>       console.log(`✅ Cookies loaded successfully from ${cookieFilePath}.`);
>       return cookieFileContent;
>     } catch (error) {
>       console.error('CRITICAL: Error reading cookie file:', error);
>       return '';
>     }
> }
> 
> async function main() {
>     let videoId: string | undefined;
> 
>     try {
>         console.log("Initializing YouTube client...");
>         const cookie = await getCookieFileContent(COOKIE_FILE_PATH);
>         const yt = await Innertube.create({ cookie, cache: new UniversalCache(false) });
> 
>         console.log(`Searching YouTube Music for "${SEARCH_QUERY}"...`);
>         const search = await yt.music.search(SEARCH_QUERY, { type: 'song' });
> 
>         if (!search.songs?.contents.length) {
>             throw new Error(`Could not find any song results for "${SEARCH_QUERY}".`);
>         }
> 
>         const songToDownload = search.songs.contents[0];
>         videoId = songToDownload.id;
>         const songTitle = songToDownload.title || 'Untitled Song';
> 
>         if (!videoId) {
>             throw new Error('Could not extract video ID from search results.');
>         }
> 
>         console.log(`\nFound: "${songTitle}" (ID: ${videoId}). Fetching info...`);
>         const info = await yt.getInfo(videoId, { client: 'TV' });
> 
>         const infoJsonPath = join(process.cwd(), `zzz.json`);
>         await Bun.write(infoJsonPath, JSON.stringify(info, null, 2));
>         console.log(`✅ Full getInfo response saved to: ${infoJsonPath}`);
> 
>         console.log('Useing Manual Decipher from `getInfo`');
>         try {
>             const format = info.streaming_data?.formats.find(f => f.itag === TARGET_ITAG);
>             if (!format) {
>                 throw new Error(`Could not find format with itag ${TARGET_ITAG}.`);
>             }
>             if (!format.signature_cipher && !format.cipher) {
>                 throw new Error(`Found itag ${TARGET_ITAG}, but it does not contain a cipher.`);
>             }
> 
>             console.log(`Found itag ${TARGET_ITAG} with a cipher. Attempting to decipher...`);
>             const decipheredUrl = format.decipher();
>             
>             if (!decipheredUrl) {
>                 throw new Error('The .decipher() method was unsuccessful and returned an empty string.');
>             }
>             
>             console.log('\n✅ SUCCESS: Manually deciphered URL:');
>             console.log(decipheredUrl);
>             return;
> 
>         } catch (error) {
>             console.error('\n❌ FAILED: An error occurred during manual deciphering.');
>             console.error(`❌ Exact Error: ${error instanceof Error ? error.message : String(error)}`);
>         }
>     } catch (error) {
>         console.error('Error:', error);
>         process.exit(1);
>     }
> }
> 
> main();
> ```
> 
> I am receiving:
> ```tex
> Initializing YouTube client...
> ✅ Cookies loaded successfully from cookies1.txt.
> Searching YouTube Music for "Hey Jude"...
> 
> Found: "Hey Jude" (ID: mQER0A0ej0M). Fetching info...
> ✅ Full getInfo response saved to: /home/admin/zzz.json
> 
> Using Manual Decipher from `getInfo`
> Found itag 18 with a cipher. Attempting to decipher...
> 
> ❌ FAILED: An error occurred during manual deciphering.
> ❌ Exact Error: The .decipher() method was unsuccessful and returned an empty string.
> ```
> 
> How do I decipher urls correctly?
> 
> ### Other details
> 
> _No response_
> 
> ### Checklist
> 
> - [x] I am running the latest version.
> - [x] I checked the documentation and found no answer.
> - [x] I have searched the existing issues and made sure this is not a duplicate.
> - [x] I have provided sufficient information.

This was fixed in the latest release, you need to clear the cache, if you don't it will still load the broken cache entry

**Comment by theone2277** [comment]
> > ### Question
> > I have encountered a bug.
> > Here is the code:
> > import { Innertube, UniversalCache } from 'youtubei.js';
> > import { join } from 'node:path';
> > 
> > const SEARCH_QUERY = 'Hey Jude';
> > const TARGET_ITAG = 18;
> > const COOKIE_FILE_PATH = 'cookies.txt';
> > 
> > async function getCookieFileContent(cookieFilePath: string): Promise<string> {
> >     const cookieFile = Bun.file(cookieFilePath);
> >     if (!(await cookieFile.exists())) {
> >       console.warn(
> >         `🔴 WARNING: Cookie file not found at '${cookieFilePath}'. The application will run in unauthenticated mode.`
> >       );
> >       return '';
> >     }
> >     try {
> >       const cookieFileContent = await cookieFile.text();
> >       console.log(`✅ Cookies loaded successfully from ${cookieFilePath}.`);
> >       return cookieFileContent;
> >     } catch (error) {
> >       console.error('CRITICAL: Error reading cookie file:', error);
> >       return '';
> >     }
> > }
> > 
> > async function main() {
> >     let videoId: string | undefined;
> > 
> >     try {
> >         console.log("Initializing YouTube client...");
> >         const cookie = await getCookieFileContent(COOKIE_FILE_PATH);
> >         const yt = await Innertube.create({ cookie, cache: new UniversalCache(false) });
> > 
> >         console.log(`Searching YouTube Music for "${SEARCH_QUERY}"...`);
> >         const search = await yt.music.search(SEARCH_QUERY, { type: 'song' });
> > 
> >         if (!search.songs?.contents.length) {
> >             throw new Error(`Could not find any song results for "${SEARCH_QUERY}".`);
> >         }
> > 
> >         const songToDownload = search.songs.contents[0];
> >         videoId = songToDownload.id;
> >         const songTitle = songToDownload.title || 'Untitled Song';
> > 
> >         if (!videoId) {
> >             throw new Error('Could not extract video ID from search results.');
> >         }
> > 
> >         console.log(`\nFound: "${songTitle}" (ID: ${videoId}). Fetching info...`);
> >         const info = await yt.getInfo(videoId, { client: 'TV' });
> > 
> >         const infoJsonPath = join(process.cwd(), `zzz.json`);
> >         await Bun.write(infoJsonPath, JSON.stringify(info, null, 2));
> >         console.log(`✅ Full getInfo response saved to: ${infoJsonPath}`);
> > 
> >         console.log('Useing Manual Decipher from `getInfo`');
> >         try {
> >             const format = info.streaming_data?.formats.find(f => f.itag === TARGET_ITAG);
> >             if (!format) {
> >                 throw new Error(`Could not find format with itag ${TARGET_ITAG}.`);
> >             }
> >             if (!format.signature_cipher && !format.cipher) {
> >                 throw new Error(`Found itag ${TARGET_ITAG}, but it does not contain a cipher.`);
> >             }
> > 
> >             console.log(`Found itag ${TARGET_ITAG} with a cipher. Attempting to decipher...`);
> >             const decipheredUrl = format.decipher();
> >             
> >             if (!decipheredUrl) {
> >                 throw new Error('The .decipher() method was unsuccessful and returned an empty string.');
> >             }
> >             
> >             console.log('\n✅ SUCCESS: Manually deciphered URL:');
> >             console.log(decipheredUrl);
> >             return;
> > 
> >         } catch (error) {
> >             console.error('\n❌ FAILED: An error occurred during manual deciphering.');
> >             console.error(`❌ Exact Error: ${error instanceof Error ? error.message : String(error)}`);
> >         }
> >     } catch (error) {
> >         console.error('Error:', error);
> >         process.exit(1);
> >     }
> > }
> > 
> > main();
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am receiving:
> > Initializing YouTube client...
> > ✅ Cookies loaded successfully from cookies1.txt.
> > Searching YouTube Music for "Hey Jude"...
> > 
> > Found: "Hey Jude" (ID: mQER0A0ej0M). Fetching info...
> > ✅ Full getInfo response saved to: /home/admin/zzz.json
> > 
> > Using Manual Decipher from `getInfo`
> > Found itag 18 with a cipher. Attempting to decipher...
> > 
> > ❌ FAILED: An error occurred during manual deciphering.
> > ❌ Exact Error: The .decipher() method was unsuccessful and returned an empty string.
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How do I decipher urls correctly?
> > ### Other details
> > _No response_
> > ### Checklist
> > 
> > 
> > 
> > 
> > 
> > * [x]  I am running the latest version.[x]  I checked the documentation and found no answer.[x]  I have searched the existing issues and made sure this is not a duplicate.[x]  I have provided sufficient information.
> 
> This was fixed in the latest release, you need to clear the cache, if you don't it will still load the broken cache entry

I deleted the cache file/folder, I am unsure whether it was a file or folder named youtubeixyz, earlier. 

```tex
admin@ip-132-31-57-9:~$ ls .cache
5ec65609  6742b2b9  9f49a55a  b66835e2  ffmpeg-static-nodejs  fontconfig  node  node-gyp  pnpm  puppeteer  yt-dlp
admin@ip-132-31-57-9:~$
```

Additionally, I think cache: new UniversalCache(false) disables caches to be re-used.

**Comment by absidue** [comment]
> Additionally, I think cache: new UniversalCache(false) disables caches to be re-used.

No, if you don't want to use a cache, you need to remove the `cache` parameter from the call to `Innertube.create()` entirely.

**Comment by theone2277** [comment]
> > Additionally, I think cache: new UniversalCache(false) disables caches to be re-used.
> 
> No, if you don't want to use a cache, you need to remove the `cache` parameter from the call to `Innertube.create()` entirely.

I have completely removed cache use from the code by applying:
import { Innertube } from 'youtubei.js';
and
        const yt = await Innertube.create({ cookie });

However, I still receive:
```tex
admin@ip-132-31-57-9:~$ bun err
Initializing YouTube client...
✅ Cookies loaded successfully from cookies1.txt.
Searching YouTube Music for "Hey Jude"...

Found: "Hey Jude" (ID: mQER0A0ej0M). Fetching info...
✅ Full getInfo response saved to: /home/admin/zzz.json
Useing Manual Decipher from `getInfo`
Found itag 18 with a cipher. Attempting to decipher...

❌ FAILED: An error occurred during manual deciphering.
❌ Exact Error: The .decipher() method was unsuccessful and returned an empty string.
admin@ip-132-31-57-9:~$ bun info youtubei.js
youtubei.js@15.1.0 | MIT | deps: 3 | versions: 133
A JavaScript client for YouTube's private API, known as InnerTube.
```

**Comment by absidue** [comment]
You need to pass the `Player` (`yt.session.player`) object to the decipher method.

>The deciphered URL as a string. If no player is provided, returns the original URL or an empty string.

https://ytjs.dev/api/namespaces/Misc/classes/Format.html#returns-1
